### ISSUE TITLE
What about to have some method to convert csv to xls 

### ISSUE THREAD

**Issue by talesmgodois** [dixieio/zipcelx#62]
I was thinking about have a method to create, from csv a xls file. In this case, all types would be strings

**Comment by egeriis** [comment]
That should be pretty easy to add on top of `zipcelx`. Write or use some kind of CSV parser, map that result into the `zipcelx` format.

It would be out of scope for `zipcelx` though.

**Comment by talesmgodois** [comment]
Yes and I it was easy haha. I just thought it would be nice this feature inside of zipcelx. But it is ok if is out of scope.

**Comment by egeriis** [comment]
We've got a very explicit goal statement in the README:

> Generate XLSX files in the browser, with minimal footprint. The vision is to provide the smallest possible package for generating valid XLSX files in the browser.

I'm afraid this will probably add to the footprint of zipcelx.

Closing issue, feel free to reopen if you feel there are more to discuss :)
