### ISSUE TITLE
XLSX file does not appear to be zipped

### ISSUE THREAD

**Issue by kaeverens** [dixieio/zipcelx#72]
I can't get a simple test file to load (numbers, letters). When examining the Zipcelx export in comparison to an XLSX sample file [from here](https://file-examples.com/index.php/sample-documents-download/sample-xls-download/), I can see that the Zipcelx file has plain raw XML in the file where I expect to see zipped material.

In this image, the Zipcelx export is on the left:

![image](https://user-images.githubusercontent.com/2878523/87461761-c37bdf00-c606-11ea-9d55-1810e0d3ff79.png)

This file does not load in LibreOffice, and if I upload to an online converter, it also fails to convert.

The (broken) file is here: https://www.dropbox.com/s/llfh4vz4aadc0a1/job.xlsx?dl=0

**Comment by egeriis** [comment]
Can you share a reproducible code example? Thanks
