### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by pytdata** [dixieio/zipcelx#89]
Hello guyz,
so I  included the script tag in my code:

`<script src="../zipcelx/lib/legacy.js"></script>`

and also tried testing the library with this short code:

`<script>

    textXLSX=()=>{
        const exports = {
            filename: 'general-ledger-Q1',
            sheet: {
                data: [
                [{
                    value: 'Income - Webshop',
                    type: 'string'
                }, {
                    value: 1000,
                    type: 'number'
                }]
                ]
            }
        };
        zipcelx(exports);
    }

    textXLSX()
</script>`

This is he error am getting in the console:
`legacy.js:1 Uncaught ReferenceError: exports is not defined`

Kindly help a brother here. Thanks.

**Comment by egeriis** [comment]
If you plan to use the library without a build pipeline, you should use the
`standalone.js` file

**Comment by pytdata** [comment]
Thanks @egeriis. :)
The error is gone but not excel file was generated.

**Comment by egeriis** [comment]
Difficult to help without any debugging information :) Are you seeing any errors?

**Comment by pytdata** [comment]
> Difficult to help without any debugging information :) Are you seeing any errors?

no please no errors at all

**Comment by pytdata** [comment]
Hello @egeriis, everything is working just fine.
 
I have a base b4 encoded image, can it be used as a cell value, am trying to add image to the excel

**Comment by IlyaDiallo** [comment]
> I have a base b4 encoded image, can it be used as a cell value, am trying to add image to the excel

No, just text or num values
